# 14.plot_wet_dry.R — Plot dual-axis track plots and offset scan lines for wet-lab vs dry-model comparison.
#
# Reads the stats and offset CSVs generated by 13.offset_wet_dry.py.
# Dynamically joins wet-lab and dry-model original data in memory to avoid generating intermediate track CSVs.
# 
# Generates:
#   1. offset_wet_dry_[tool].pdf: Line charts showing r, with best points highlighted & annotated.
#   2. compare_wet_dry_[tool].pdf: Dual-axis track plots at the BEST offset.
#
# conda env: system R

library(ggplot2)
library(grid)
library(gridExtra)

log <- function(msg) {
  cat(sprintf("[%s] %s\n", Sys.time(), msg), flush=TRUE)
}

# ================= Configuration =================
PROJECT <- "/data/cai801/data/HKUcas"
WET_DIR <- file.path(PROJECT, "result/08.manuscript_03/partA/01.clean_wet")
MODEL_DIR <- file.path(PROJECT, "result/08.manuscript_03/partA/03.aligned_pred")
FIGURE_DIR <- file.path(PROJECT, "result/08.manuscript_03/partA/04.offset_cor")

# Analytical settings
COR_METHOD <- "spearman"  # Options: "spearman" or "pearson"
ALIGN_BY <- "end_pos"     # Options: "end_pos" or "start_pos"

TOOL_PREFIXES <- list(
  "CasRx_day5" = "02",
  "shRNAone" = "03",
  "PspCas13b" = "04"
)

REGION_COLORS <- c("5'UTR" = "#440154", "CDS" = "#21908C", "3'UTR" = "#FDE725")

format_p <- function(p) {
  if (is.na(p)) return("NA")
  if (p < 1e-10) return("< 1e-10")
  if (p < 1e-5) return("< 1e-5")
  if (p < 1e-3) return("< 1e-3")
  sprintf("%.4f", p)
}

method_label <- tools::toTitleCase(COR_METHOD)
log(sprintf("14. Building wet-vs-dry plots (method: %s, align by: %s)", method_label, ALIGN_BY))

for (tool in names(TOOL_PREFIXES)) {
  prefix <- TOOL_PREFIXES[[tool]]
  
  # File paths
  offset_file <- file.path(FIGURE_DIR, paste0(prefix, ".offset_wet_dry_", tool, ".csv"))
  stats_file <- file.path(FIGURE_DIR, paste0(prefix, ".compare_wet_dry_", tool, ".csv"))
  wet_file <- file.path(WET_DIR, paste0("TTR_", tool, "_clean.csv"))
  
  if (!file.exists(stats_file) || !file.exists(offset_file) || !file.exists(wet_file)) {
    log(sprintf("  [SKIP] Files missing for %s", tool))
    next
  }
  
  df_offset <- read.csv(offset_file)
  df_stats <- read.csv(stats_file)
  df_wet <- read.csv(wet_file)
  
  # Color mapping for regions
  df_wet$region_col <- ifelse(df_wet$region %in% names(REGION_COLORS), 
                              REGION_COLORS[df_wet$region], "#999999")
  
  # Prepare labels for the offset plot
  df_stats$p_fmt <- sapply(df_stats$p_value, format_p)
  df_stats$label_text <- sprintf("%d nt\nr=%.3f, p=%s", 
                                 df_stats$best_offset, 
                                 df_stats$cor_r, 
                                 df_stats$p_fmt)
  
  # ================= 1. Plot Offset Scan Line Chart =================
  p_offset <- ggplot(df_offset, aes(x = offset, y = correlation_r, color = model, group = model)) +
    geom_vline(xintercept = 0, color = "gray60", linetype = "dashed", alpha = 0.8) +
    geom_line(linewidth = 1) +
    geom_point(size = 1.2, alpha = 0.6) +
    # Highlight the BEST offset points on the peaks
    geom_point(data = df_stats, 
               aes(x = best_offset, y = cor_r, color = dry_model), 
               inherit.aes = FALSE, size = 3.5, shape = 21, fill = "white", stroke = 1.2, 
               show.legend = FALSE) +
    # Add text annotations for the best offsets
    geom_text(data = df_stats, 
              aes(x = best_offset, y = cor_r, label = label_text), 
              inherit.aes = FALSE, color = "black", size = 2.8, 
              vjust = -0.4, hjust = -0.15, lineheight = 0.9, 
              show.legend = FALSE) +
    scale_color_brewer(palette = "Set1") +
    coord_cartesian(clip = "off") + # Prevent labels near the edge from being cut off
    labs(
      title = sprintf("%s — Wet vs Dry Offset Scan (%s)", tool, method_label),
      x = sprintf("Offset of Shift (nt) relative to Base (Aligned by %s)", ALIGN_BY),
      y = sprintf("%s r", method_label),
      color = "Model"
    ) +
    theme_minimal() +
    theme(
      plot.title = element_text(size = 12, face = "bold"),
      legend.position = "bottom",
      panel.grid.minor = element_blank(),
      plot.margin = margin(t = 15, r = 30, b = 10, l = 10) # Add some margin for text
    )
  
  offset_pdf_path <- file.path(FIGURE_DIR, paste0(prefix, ".offset_wet_dry_", tool, ".pdf"))
  pdf(offset_pdf_path, width = 8, height = 4)
  print(p_offset)
  dev.off()
  log(sprintf("  Saved offset plot: %s", basename(offset_pdf_path)))
  
  # ================= 2. Plot Dual-axis Track Plots =================
  models <- unique(df_stats$dry_model)
  plots <- list()
  
  for (m_name in models) {
    dry_file <- file.path(MODEL_DIR, paste0(m_name, "_aligned.csv"))
    if (!file.exists(dry_file)) next
    
    df_dry <- read.csv(dry_file)
    
    # Extract only the needed columns and rename dynamic ALIGN_BY to "pos_align"
    df_dry_sub <- df_dry[, c(ALIGN_BY, "prediction_score")]
    colnames(df_dry_sub) <- c("pos_align", "prediction_score")
    
    # Handle possible duplicate prediction scores at the same coordinate
    df_dry_agg <- aggregate(prediction_score ~ pos_align, data = df_dry_sub, FUN = mean)
    
    # Get best offset for this specific model
    m_stats <- subset(df_stats, dry_model == m_name)
    best_off <- m_stats$best_offset[1]
    
    # To align, the rule is: wet_pos + offset = dry_pos
    df_dry_agg$target_wet_pos <- df_dry_agg$pos_align - best_off
    
    # Left join to preserve all wet lab positions (ensures identical gray background)
    df_m <- merge(df_wet, df_dry_agg, by.x = ALIGN_BY, by.y = "target_wet_pos", all.x = TRUE)
    df_m <- df_m[order(df_m[[ALIGN_BY]]), ]
    
    annot_text <- sprintf("Best Offset: %d nt\nr = %.3f, p = %s", 
                          best_off, 
                          m_stats$cor_r[1], 
                          format_p(m_stats$p_value[1]))
    
    # Calculate mapping from Prediction Score to log2FC limits for dual axis
    y_min <- min(df_m$mean_log2FC, na.rm = TRUE)
    y_max <- max(df_m$mean_log2FC, na.rm = TRUE)
    if (y_min == y_max) { y_min <- y_min - 1; y_max <- y_max + 1 }
    
    p_min <- min(df_m$prediction_score, na.rm = TRUE)
    p_max <- max(df_m$prediction_score, na.rm = TRUE)
    
    if (is.infinite(p_min) || is.na(p_min) || p_min == p_max) {
      df_m$pred_mapped <- NA
      p_range <- 1
    } else {
      p_range <- p_max - p_min
      df_m$pred_mapped <- y_min + (df_m$prediction_score - p_min) / p_range * (y_max - y_min)
    }
    
    # Plotting
    p <- ggplot(df_m, aes(x = .data[[ALIGN_BY]])) +
      # Background: Wet lab log2FC
      geom_ribbon(aes(ymin = y_min, ymax = mean_log2FC), fill = "#CCCCCC", alpha = 0.5) +
      # Foreground: Dry model score (line)
      geom_line(aes(y = pred_mapped, color = region_col, group = 1), linewidth = 0.8) +
      scale_color_identity() +
      annotate("text", x = Inf, y = Inf, label = annot_text, hjust = 1.05, vjust = 1.1, 
               size = 3.5, family = "mono") +
      # Dual axis configuration
      scale_y_continuous(
        name = expression("Wet Lab " ~ log[2][FC]),
        sec.axis = sec_axis(~ (. - y_min) / (y_max - y_min) * p_range + p_min, 
                            name = "Prediction Score")
      ) +
      labs(title = sprintf("%s vs %s", tool, m_name)) +
      theme_minimal() +
      theme(
        plot.title = element_text(size = 11, face = "bold"),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 9),
        panel.grid.minor = element_blank()
      )
    
    plots[[m_name]] <- p
  }
  
  if (length(plots) > 0) {
    compare_pdf_path <- file.path(FIGURE_DIR, paste0(prefix, ".compare_wet_dry_", tool, ".pdf"))
    pdf(compare_pdf_path, width = 8.27, height = 1.5 * length(plots))
    grid.arrange(grobs = plots, ncol = 1)
    dev.off()
    log(sprintf("  Saved track plot : %s", basename(compare_pdf_path)))
  }
}

log("14. Done.")