#!/usr/bin/env python3
"""
partA.06.run_RNAxs.py — RNAxs target site accessibility prediction on NM_000371.4.

This script automates the standalone RNAxs.pl execution by bypassing its
hard filters (setting all thresholds to 0) to obtain continuous scores 
(Acc 8, Acc 16, etc.) for all possible 19 nt siRNAs across the transcript.

conda env: siRNA_rnaxs (has pandas, viennarna, perl-algorithm-diff)
"""

import os
import sys
import subprocess
import tempfile
import pandas as pd
from datetime import datetime

# ================= 1. Global Configurations =================
PROJECT = "/data/cai801/data/HKUcas"
DATA_DIR = os.path.join(PROJECT, "data")
RESULT_DIR = os.path.join(PROJECT, "result/08.manuscript_03/partA/02.original_pred")
FASTA = os.path.join(DATA_DIR, "NM_000371.4.fasta")
ACC = "NM_000371.4"
LEN = 19
OUT_CSV = os.path.join(RESULT_DIR, f"RNAxs_{LEN}_{ACC}.csv")

RNAXS_DIR = os.path.join(PROJECT, "software/RNAxs")
RNAXS_PL = os.path.join(RNAXS_DIR, "RNAxs.pl")

os.makedirs(RESULT_DIR, exist_ok=True)


def log(msg):
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {msg}", flush=True)


def reverse_complement(seq):
    """Convert target RNA sequence to DNA-format siRNA guide."""
    mapping = str.maketrans("ACGTUacgtu", "TGCAATGCAA")
    return seq.translate(mapping)[::-1]


# ================= 2. Main Execution =================
log("06. RNAxs (Accessibility-based): NM_000371.4")
log(f"    Guide length: {LEN} nt (native siRNA length)")

# Read FASTA
with open(FASTA) as f:
    lines = f.readlines()
# RNAxs expects DNA format for calculations, replace U with T
seq_flat = "".join(line.strip().upper().replace('U', 'T') for line in lines if not line.startswith(">"))

log(f"    Transcript length: {len(seq_flat)} nt")

# Use a temporary directory to contain RNAplfold's intermediate files (e.g. sequence_lunp)
with tempfile.TemporaryDirectory(dir=RESULT_DIR) as tmpdir:
    tmp_fasta = os.path.join(tmpdir, "target.fasta")
    tmp_sirna = os.path.join(tmpdir, "sirna_list.txt")
    tmp_out = os.path.join(tmpdir, "rnaxs_out.txt")

    # 1. Write the target FASTA
    with open(tmp_fasta, "w") as f:
        f.write(f">{ACC}\n{seq_flat}\n")

    # 2. Generate all possible sliding windows & siRNA reverse complements
    records = []
    sirna_list = []
    for i in range(len(seq_flat) - LEN + 1):
        target_sub = seq_flat[i:i + LEN]
        spacer = reverse_complement(target_sub)
        
        sirna_list.append(spacer)
        records.append({
            'transcript_id': ACC,
            'position': i + 1,  # 1-based start (5' end of target)
            'guide': spacer
        })

    # Write the siRNA list for RNAxs -c validation
    with open(tmp_sirna, "w") as f:
        f.write("\n".join(sirna_list) + "\n")

    # 3. Execute RNAxs.pl with all thresholds set to 0 to bypass hard filtering
    cmd = [
        "perl", RNAXS_PL,
        "-s", tmp_fasta,
        "-c", tmp_sirna,
        "-t", "0", "-u", "0", "-e", "0", "-a", "0", "-f", "0", "-g", "0"
    ]

    log(f"    Invoking RNAxs.pl in background...")
    try:
        # Run inside tmpdir so that local files generated by RNAplfold stay contained
        with open(tmp_out, "w") as out_f:
            subprocess.run(cmd, cwd=tmpdir, stdout=out_f, stderr=subprocess.PIPE, check=True)
    except subprocess.CalledProcessError as e:
        log(f"    ERROR running RNAxs: {e.stderr.decode()}")
        sys.exit(1)

    # 4. Parse the generated text table
    rnaxs_res = []
    with open(tmp_out, "r") as f:
        for line in f:
            line = line.strip()
            # Skip empty lines, headers, or error messages
            if not line or line.startswith("RANK") or line.startswith("no siRNA"):
                continue
            
            parts = line.split()
            if len(parts) >= 10:
                rnaxs_res.append({
                    'guide': parts[3],
                    # RNAxs Pos is the 3' end of the target window. Map it back to 5' start.
                    'position_rnaxs': int(parts[1]) - LEN + 1,
                    'RNAxs_Acc8': float(parts[4]),
                    'RNAxs_Acc16': float(parts[5]),
                    'RNAxs_AsyE': float(parts[6]),
                    'RNAxs_AsyS': float(parts[7]),
                    'RNAxs_SelfFld': float(parts[8]),
                    'RNAxs_FreeEnd': float(parts[9]),
                })

# ================= 3. Merge & Export =================
df_base = pd.DataFrame(records)
df_rnaxs = pd.DataFrame(rnaxs_res)

if not df_rnaxs.empty:
    # Deduplicate in case of perfectly repeating sequences
    df_rnaxs = df_rnaxs.drop_duplicates(subset=['position_rnaxs', 'guide'])
    
    # Merge on position and guide sequence
    df = pd.merge(df_base, df_rnaxs, left_on=['position', 'guide'], right_on=['position_rnaxs', 'guide'], how='left')
    df.drop(columns=['position_rnaxs'], inplace=True)

    # Sort primarily by Acc 16 (the most critical RNAxs accessibility metric), then Acc 8
    df = df.sort_values(by=['RNAxs_Acc16', 'RNAxs_Acc8'], ascending=[False, False])
    
    # Rank generation based on Acc16
    df['rank'] = df['RNAxs_Acc16'].rank(method='min', ascending=False)
    
    df.to_csv(OUT_CSV, index=False)
    log(f"    {len(df)} predictions merged and evaluated -> {os.path.basename(OUT_CSV)}")
else:
    log("    WARNING: No predictions were parsed from RNAxs output.")

log("06. Done.")